---
title: "pra"
output: html_document
date: "2023-06-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr) 


# 3개월 등락률 데이터 
data <- read_excel("C:/Users/jbnu/Downloads/data_5621_20230610.xlsx")
dt<-data.frame(data)
dt[dt$종목명=="한화에어로스페이스",]

# 6개월 등락률 데이터
data2<-read_excel("C:/Users/jbnu/Downloads/data_2154_20230610.xlsx")
dt2<-data.frame(data2)

# 23/06/09 기준 kospi 데이터
kospi<-read.csv("C:/Users/jbnu/Documents/R file/basic/kospi.csv")
kospi <- kospi %>%
  select(종목명, 종목코드, 상장주식수, 현재가, 시가총액)

kospi$rate1<-NA
count<-0
for (i in 1:400){
  if (any(dt[,1]==kospi[,2][i])==TRUE){
    kospi[i,]$rate1<-dt[dt[,1]==kospi[,2][i],]$등락률
    count<-count+1
  }
  if (count==200) { # kospi200 기업까지만 조사
    print(i)
    break
  }
}

kospi$rate2<-NA
count<-0
for (i in 1:400){
  if (any(dt2[,1]==kospi[,2][i])==TRUE){
    kospi[i,]$rate2<-dt2[dt2[,1]==kospi[,2][i],]$등락률
    count<-count+1
  }
  if (count==200) { # kospi200 기업까지만 조사
    print(i)
    break
  }
}



# 3개월 등락율을 추가한 kospi200 기업
kospi200<-kospi[!is.na(kospi$rate1),]

# 등락율이 가장 높은 종목
kospi200[kospi200$rate1==max(kospi200$rate1),]
kospi200[kospi200$rate2==max(kospi200$rate2),]

# 등락율이 가장 낮은 종목
kospi200[kospi200$rate1==min(kospi200$rate1),]
kospi200[kospi200$rate2==min(kospi200$rate2),]

##### 3개월 #####
# 3개월 등락율 히스토그램
hist(kospi200$rate1, breaks = seq(min(kospi200$rate1),max(kospi200$rate1)+1,1),
     xlim = c(min(kospi200$rate1),max(kospi200$rate1)),xaxt = "n")
axis(side = 1, at = seq(-30, 190, by = 10))
abline(v=0,col='red',lwd=2)



# 등락율이 감소한 종목 확인
kospi200[kospi200$rate1<0,]
order200<-kospi200[order(kospi200$rate1),]

# 기여도(시가총액)을 계산하여 구한 kospi의 평균 등락율
sum(kospi200$시가총액*kospi200$rate1)/sum(kospi200$시가총액)


##### 6개월 #####
# 6개월 등락율 히스토그램
hist(kospi200$rate2, breaks = seq(min(kospi200$rate2),max(kospi200$rate2)+1,1),
     xlim = c(min(kospi200$rate2),max(kospi200$rate2)),xaxt = "n")
axis(side = 1, at = seq(-60,280 , by = 10))
abline(v=0,col='red',lwd=2)



# 등락율이 감소한 종목 확인
kospi200[kospi200$rate2<0,]
order200_2<-kospi200[order(kospi200$rate2),]

# 기여도(시가총액)을 계산하여 구한 kospi의 평균 등락율
sum(kospi200$시가총액*kospi200$rate2)/sum(kospi200$시가총액)


#
kospi200[kospi200$rate1>0&kospi200$rate2<0,]



```

